config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'playlists#index'
  resources :playlists
  resources :songs, only: [:index, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :voted_songs
  validates :title, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :voted_songs
  validates :name, :artist, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :playlists
  validates :first_name, :last_name, :spotify_account, presence: true
end

app/models/voted_song.rb
class VotedSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index
    @playlists = Playlist.all
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user = current_user
    if @playlist.save
      redirect_to playlists_path, notice: 'Playlist was successfully created.'
    else
      render :new
    end
  end

  def edit
    @playlist = Playlist.find(params[:id])
  end

  def update
    @playlist = Playlist.find(params[:id])
    @playlist.update(playlist_params)
    redirect_to @playlist, notice: 'Playlist was successfully updated.'
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy
    redirect_to playlists_path, notice: 'Playlist was successfully deleted.'
  end

  private

  def playlist_params
    params.require(:playlist).permit(:title)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def new
    @songs = Song.new
  end

  def create
    @song = Song.new(song_params)
    @song.user = current_user
    if @song.save
      redirect_to songs_path, notice: 'song was successfully created.'
    else
      render :new
    end
  end

  private

  def songs_params
    params.require(:song).permit(:name, :artist, :album)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="wrapper">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/playlists/delete.html.erb
<h1>Playlists#delete</h1>
<p>Find me in app/views/playlists/delete.html.erb</p>

app/views/playlists/edit.html.erb
<div class="back-btn">
  <%= link_to "Back to all playlists", playlists_path, class: 'btn btn-light' %>
</div>

<h1>Edit the playlist</h1>

<%= simple_form_for [@playlist] do |f| %>
<%= f.input :title %>
<div class="inline-btn">
  <%= f.submit "Change the title", class: 'btn btn-primary' %>
<% end %>
  <div class="action">
    <%= link_to "Cancel", playlists_path, class: 'btn btn-light' %>
  </div>
</div>

app/views/playlists/index.html.erb
<div class="inline-title-btn">
  <div>
    <h1>All playlists</h1>
  </div>
  <div>
    <p> <%= link_to "+ Add a new playlist", new_playlist_path, class: 'btn btn-primary' %></p>
  </div>
</div>


<% @playlists.each do |playlist| %>
<div class="inline-action">
  <div>
    <h4> <%= link_to playlist.title, playlist_path(playlist) %> </h4>
  </div>
  <div class="action">
    <p> <%= link_to "Edit", edit_playlist_path(playlist) %></p>
    <p> <%= link_to "Delete", playlist_path(playlist), method: :delete, data: { confirm: "Are you sure?" } %></p>
  </div>
</div>
<% end %>

app/views/playlists/new.html.erb
<div class="back-btn">
  <%= link_to "Back to all playlists", playlists_path, class: 'btn btn-light' %>
</div>

<h1>New Playlist</h1>

<%= simple_form_for [@playlist] do |f| %>
<%= f.input :title, placeholder: "Fête de Caro" %>
<%= f.submit "Add a playlist", class: 'btn btn-primary' %>
<% end %>

app/views/playlists/show.html.erb
<div class="back-btn">
  <%= link_to "Back to all playlists", playlists_path, class: 'btn btn-light' %>
</div>


<div class="inline-action">
  <h1><%= @playlist.title %></h1>
  <div class="action">
    <p> <%= link_to "Edit", edit_playlist_path(@playlist) %></p>
    <p> <%= link_to "Delete", playlist_path(@playlist), method: :delete, data: { confirm: "Are you sure?" } %></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to songs_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "My playlists", playlists_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://res.cloudinary.com/ddptqqjng/image/upload/v1528054628/Patrick-Vignaud.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

<%= form_tag songs_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a song"
  %>
<% end %>